# Site settings
title: Swoop Labs
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Swoop Labs
baseurl: "/swoop-website" # the subpath of your site, e.g. /blog/
url: "http://longhairedmedia.github.io" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

permalink: /blog/:categories/:title
paginate_path: "/blog/page:num/"
paginate: 6

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
highlighter: rogue
